---
- name: test
  hosts: localhost
  gather_facts: false
  vars:
    api_info: &api_info
      host: '10.4.255.5'
      username: 'admin'
      password: 'C1sc0123'
      validate_certs: false

  tasks:
  - name: ACI Tenant
    aci_tenant:
        <<: *api_info
        tenant: "vs_code_testing" # required. The name of the tenant.
        state: present # not required. choices: absent;present;query. Use C(present) or C(absent) for adding or removing.,Use C(query) for listing an object or multiple objects.
        